### ISSUE TITLE
doesn't like skooma

### ISSUE THREAD

**Issue by DarkWiiPlayer** [daelvn/daelvn#13]
It seems this user doesn't like the name `skooma` for my project, please fix.

Steps to reproduce:

1. Make a new Lua module with an awesome TES reference as a name
2. Wait for the bullying to start

I'd open a pull request, but I don't understand any of the code (Maybe this project should be ported from DNA to Haskell in the future).

**Comment by daelvn** [comment]
This issue does not belong here. Take it to [god/man](https://github.com/god/man) instead.
